import type { FormatLandingConfig } from "@/components/format-landing-page";

export const formatPages = {
  pptx: {
    path: "/pptx-to-markdown",
    title: "Convert PowerPoint PPTX to Markdown locally",
    extensions: "PPTX",
    summary: "Open a PowerPoint presentation and turn slide titles, text, notes, and tables into editable Markdown without uploading the file.",
    description: "Markdown Lens reads modern PowerPoint packages in your browser, keeps slide boundaries, and extracts embedded images as local document assets.",
    preserves: ["Slide order and slide headings", "Text shapes and speaker notes", "Readable tables and hyperlinks", "Embedded slide images as local assets"],
    limitations: ["Animations, transitions, theme styling, and exact object placement are not represented.", "Charts and diagrams may require manual descriptions.", "Legacy .ppt files must first be exported as .pptx."],
    steps: ["Choose a .pptx file in the workspace.", "Review slide-by-slide conversion progress and warnings.", "Edit, preview, and export the generated Markdown."],
    faq: [
      { question: "Are PowerPoint files uploaded?", answer: "No. PPTX packages are opened and parsed locally in the browser." },
      { question: "Are slide images included?", answer: "Embedded images are stored as local document assets and can be exported with the Markdown bundle." },
    ],
    related: [
      { href: "/word-to-markdown", title: "Word to Markdown converter", description: "Convert .docx headings, lists, links, tables, and images locally." },
      { href: "/pdf-to-markdown", title: "PDF to Markdown converter", description: "Extract selectable PDF text page by page into editable Markdown." },
    ],
  },
  excel: {
    path: "/excel-to-markdown",
    title: "Convert Excel XLSX sheets to Markdown tables",
    extensions: "XLSX",
    summary: "Convert visible Excel worksheets into readable GitHub-flavored Markdown tables entirely in your browser.",
    description: "The converter reads the XLSX package directly, keeps worksheet order, resolves shared text values, leaves blank cells blank, and excludes hidden sheets by default.",
    preserves: ["Visible worksheet names and order", "Rows, columns, blank cells, and cached values", "One Markdown section per worksheet", "Wide tables with horizontal preview scrolling"],
    limitations: ["Formatting, macros, charts, and pivot-table behavior are not reproduced.", "Formula output uses the value cached in the workbook.", "Legacy .xls files require export to .xlsx."],
    steps: ["Choose a modern .xlsx workbook.", "Markdown Lens converts each visible sheet locally.", "Review wide tables and export the resulting document."],
    faq: [
      { question: "Are hidden worksheets converted?", answer: "No. Hidden worksheets are excluded by default to avoid exposing unintended content." },
      { question: "Does it calculate formulas?", answer: "No. It reads cached workbook values and does not execute spreadsheet formulas." },
    ],
    related: [
      { href: "/csv-to-markdown", title: "CSV to Markdown converter", description: "Turn comma- or tab-separated files into GitHub-flavored tables." },
      { href: "/json-to-markdown", title: "JSON to Markdown converter", description: "Pretty-print JSON locally as a fenced Markdown code block." },
    ],
  },
  html: {
    path: "/html-to-markdown",
    title: "Convert HTML files to clean Markdown",
    extensions: "HTML",
    summary: "Turn local HTML documents into editable Markdown while preserving useful headings, links, lists, tables, emphasis, and code.",
    description: "Scripts, styles, embedded frames, and forms are removed before conversion so the Markdown remains focused and safe to review.",
    preserves: ["Headings, paragraphs, lists, and blockquotes", "Links, emphasis, images, and code", "Tables that fit GitHub-flavored Markdown", "The HTML document title when available"],
    limitations: ["CSS presentation and interactive behavior are not converted.", "Complex layout containers are flattened to reading order.", "Remote images remain remote references unless downloaded separately."],
    steps: ["Open a local .html or .htm file.", "Unsafe and non-content elements are removed.", "Review and export the cleaned Markdown."],
    faq: [
      { question: "Does Markdown Lens execute scripts?", answer: "No. Script, style, frame, object, and form elements are removed before Markdown conversion." },
      { question: "Can it fetch a website URL?", answer: "This release converts local HTML files. It does not proxy or scrape remote pages." },
    ],
    related: [
      { href: "/epub-to-markdown", title: "EPUB to Markdown converter", description: "Convert unprotected EPUB chapters into one Markdown document." },
      { href: "/xml-to-markdown", title: "XML to Markdown converter", description: "Validate and pretty-print XML locally as fenced Markdown." },
    ],
  },
  csv: {
    path: "/csv-to-markdown",
    title: "Convert CSV or TSV data to a Markdown table",
    extensions: "CSV or TSV",
    summary: "Open comma- or tab-separated data and produce a clean Markdown table with quoted cells handled correctly.",
    description: "Conversion runs locally and reports malformed rows instead of silently discarding parsing problems.",
    preserves: ["Quoted cells and embedded delimiters", "Header row and source row order", "Blank values and Unicode text", "CSV and tab-separated input"],
    limitations: ["Very wide datasets may be easier to read in a spreadsheet.", "Markdown tables do not support merged cells.", "Cell formatting and data types are represented as text."],
    steps: ["Choose a .csv or .tsv file.", "Review any row-level parsing warnings.", "Edit or copy the generated GFM table."],
    faq: [
      { question: "Does it support commas inside cells?", answer: "Yes. Standards-compliant quoted cells and escaped quotes are handled." },
      { question: "Is the data uploaded?", answer: "No. Parsing and table generation happen in the browser." },
    ],
    related: [
      { href: "/excel-to-markdown", title: "Excel to Markdown converter", description: "Convert visible XLSX worksheets into Markdown tables." },
      { href: "/json-to-markdown", title: "JSON to Markdown converter", description: "Format JSON locally as a reviewable Markdown code block." },
    ],
  },
  json: {
    path: "/json-to-markdown",
    title: "Convert JSON files to readable Markdown",
    extensions: "JSON",
    summary: "Open a local JSON file and turn it into a titled Markdown document with a pretty-printed, fenced code block.",
    description: "Parsing and formatting run in the browser so API dumps, config files, and export payloads stay on the device.",
    preserves: ["Valid JSON structure", "Pretty-printed indentation", "Unicode text", "A document title from the filename"],
    limitations: ["Invalid JSON is rejected rather than repaired.", "Markdown does not execute or query the data.", "Very large payloads may be easier to inspect in a dedicated JSON viewer."],
    steps: ["Choose a .json file.", "Markdown Lens validates and pretty-prints it locally.", "Copy or export the fenced Markdown."],
    faq: [
      { question: "Is JSON uploaded?", answer: "No. The file is parsed and formatted in the browser." },
      { question: "Does it convert JSON into tables automatically?", answer: "No. This release pretty-prints JSON as a fenced code block so nested structures stay intact." },
    ],
    related: [
      { href: "/xml-to-markdown", title: "XML to Markdown converter", description: "Validate and pretty-print XML locally." },
      { href: "/csv-to-markdown", title: "CSV to Markdown converter", description: "Convert tabular text files into GitHub-flavored tables." },
    ],
  },
  xml: {
    path: "/xml-to-markdown",
    title: "Convert XML files to readable Markdown",
    extensions: "XML",
    summary: "Validate a local XML file and convert it into a Markdown document with a formatted, fenced XML block.",
    description: "Markdown Lens checks that the XML is well-formed, then rebuilds a readable representation without sending the file to a server.",
    preserves: ["Well-formed element structure", "Attributes", "Formatted XML output", "A document title from the filename"],
    limitations: ["Invalid XML is rejected with a line hint where possible.", "DTD or schema validation is not applied.", "XML presentation and processing instructions are not treated as document styling."],
    steps: ["Choose a .xml file.", "The converter validates and formats it locally.", "Review the Markdown and export it."],
    faq: [
      { question: "Does it fetch remote DTDs or entities?", answer: "No. Conversion stays local and is intended for well-formed XML documents, not network-backed entity expansion." },
      { question: "Is the XML uploaded?", answer: "No. Validation and formatting happen in the browser." },
    ],
    related: [
      { href: "/json-to-markdown", title: "JSON to Markdown converter", description: "Pretty-print JSON locally as fenced Markdown." },
      { href: "/html-to-markdown", title: "HTML to Markdown converter", description: "Convert local HTML documents into editable Markdown." },
    ],
  },
  epub: {
    path: "/epub-to-markdown",
    title: "Convert EPUB books to structured Markdown",
    extensions: "EPUB",
    summary: "Convert an EPUB’s ordered chapters and XHTML content into one editable Markdown document, locally in your browser.",
    description: "Markdown Lens follows the EPUB package spine, uses the book title when available, and keeps chapter boundaries visible.",
    preserves: ["Book title and spine chapter order", "Chapter headings, paragraphs, lists, and links", "Basic tables, emphasis, and code", "Clear separators between source chapters"],
    limitations: ["DRM-protected books cannot be opened.", "Fixed-layout EPUB presentation is flattened.", "Fonts, reading-system styling, and interactive widgets are omitted."],
    steps: ["Choose an unprotected .epub file.", "Chapters are converted in package reading order.", "Review the combined Markdown and export it."],
    faq: [
      { question: "Does EPUB conversion require an account?", answer: "No. The book is parsed locally without an account or upload." },
      { question: "Does it remove DRM?", answer: "No. Protected EPUB files are unsupported." },
    ],
    related: [
      { href: "/html-to-markdown", title: "HTML to Markdown converter", description: "Convert local HTML files into editable Markdown." },
      { href: "/pdf-to-markdown", title: "PDF to Markdown converter", description: "Extract selectable PDF text into editable Markdown." },
    ],
  },
  image: {
    path: "/image-to-markdown",
    title: "Turn images into Markdown with local OCR",
    extensions: "PNG, JPG, WebP, or BMP",
    summary: "Add an image as a local Markdown asset and optionally extract English text using OCR that runs in your browser.",
    description: "The original image is kept in the local document workspace. OCR is opt-in, cancelable, and does not send pixels to a hosted service.",
    preserves: ["Original image as a local document asset", "Image dimensions, type, and source size", "Optional locally recognized English text", "Portable Markdown-plus-assets bundle export"],
    limitations: ["OCR accuracy depends on resolution, contrast, orientation, and typography.", "The bundled OCR language is English in this release.", "OCR extracts text but does not infer chart meaning or visual semantics.", "Scanned PDFs are a different workflow and still need a dedicated OCR step before PDF conversion."],
    steps: ["Choose a supported image.", "Decide whether to run local English OCR.", "Review recognized text and export the image bundle."],
    faq: [
      { question: "Is OCR cloud-based?", answer: "No. The OCR worker and English model run locally after they are loaded from the same site origin." },
      { question: "Does it describe charts?", answer: "No. This release extracts visible text and image metadata rather than interpreting visual meaning." },
    ],
    related: [
      { href: "/pdf-to-markdown", title: "PDF to Markdown converter", description: "Convert text-based PDFs locally. Scanned PDFs still need OCR first." },
      { href: "/word-to-markdown", title: "Word to Markdown converter", description: "Convert .docx files and keep embedded images as local assets." },
    ],
  },
  zip: {
    path: "/zip-to-markdown",
    title: "Import supported files from a local ZIP archive",
    extensions: "ZIP",
    summary: "Open a ZIP archive in your browser and convert supported entries such as Markdown, Office documents, HTML, data files, and images without uploading the archive.",
    description: "Markdown Lens inspects the archive locally, enforces size and nesting limits, and converts readable entries one by one. Encrypted or unsafe archives are rejected.",
    preserves: ["Supported files found in the archive", "Original filenames as document titles", "Local conversion warnings per entry", "A bounded, reviewable import instead of a silent dump"],
    limitations: ["Only one nesting level is read.", "Archives are limited to 100 entries and 128 MB expanded.", "Encrypted ZIPs and unsupported file types are skipped or rejected.", "Each converted entry still has the same format limitations as opening that file directly."],
    steps: ["Choose a .zip file.", "Markdown Lens lists and converts supported entries locally.", "Review the resulting documents in the workspace."],
    faq: [
      { question: "Is the ZIP uploaded?", answer: "No. The archive is opened and expanded in the browser within local safety limits." },
      { question: "Does it extract every file type?", answer: "No. Only formats Markdown Lens already converts are imported, such as Markdown, PDF, DOCX, PPTX, XLSX, HTML, CSV, JSON, XML, EPUB, and supported images." },
    ],
    related: [
      { href: "/supported-formats", title: "Supported formats", description: "Compare every local conversion workflow and its limits." },
      { href: "/pdf-to-markdown", title: "PDF to Markdown converter", description: "Convert a text-based PDF directly without zipping it first." },
    ],
  },
} satisfies Record<string, FormatLandingConfig>;
