export const siteConfig = {
  name: "Markdown Lens",
  url: "https://markdownlens.ayushdev.com",
  githubUrl: "https://github.com/ayushhagarwal/markdown-lens",
  title: "Free Online Markdown Viewer & Editor | Markdown Lens",
  description:
    "Markdown Lens is a free, privacy-first online Markdown viewer and editor for previewing GitHub-flavored Markdown, Mermaid diagrams, math, code, tables, READMEs, and documentation.",
  shortDescription:
    "Preview Markdown online with GitHub-style rendering, Mermaid diagrams, math, syntax highlighting, tables, local autosave, and no account required.",
  author: {
    name: "Ayush Agarwal",
    url: "https://github.com/ayushhagarwal",
  },
  keywords: [
    "markdown editor",
    "markdown viewer",
    "online markdown editor",
    "online markdown viewer",
    "markdown application",
    "markdown tool",
    "markdown preview",
    "markdown previewer",
    "free markdown viewer",
    "markdown viewer online free",
    "online markdown preview",
    "markdown renderer",
    "markdown to html",
    "github markdown editor",
    "github flavored markdown viewer",
    "README editor",
    "README preview",
    "Mermaid markdown editor",
    "markdown math editor",
    "KaTeX markdown",
    "developer writing tool",
    "AI notes markdown",
    "privacy-first markdown editor",
  ],
  features: [
    "Live Markdown editor and preview",
    "GitHub-flavored Markdown rendering",
    "Mermaid diagram rendering",
    "KaTeX math rendering",
    "Syntax-highlighted code blocks",
    "Tables, task lists, strikethrough, and autolinks",
    "Copy Markdown and rendered HTML",
    "Download Markdown files",
    "Import local Markdown files",
    "Export rendered Markdown as standalone HTML",
    "Print or save preview as PDF",
    "Local draft autosave with no account required",
    "Keyboard shortcuts for common actions",
    "Light and dark mode",
  ],
};
