export const siteConfig = {
  name: "Markdown Lens",
  url: "https://markdownlens.ayushdev.com",
  githubUrl: "https://github.com/ayushhagarwal/markdown-lens",
  title: "Free Online Markdown Viewer & Editor | Markdown Lens",
  description:
    "Markdown Lens is a free, privacy-first Markdown viewer and editor with local PDF and Word-to-Markdown conversion, GitHub-flavored previews, diagrams, math, code, and tables.",
  shortDescription:
    "Preview Markdown or convert text-based PDFs and Word .docx files locally with GitHub-style rendering, diagrams, math, syntax highlighting, local autosave, and no account required.",
  author: {
    name: "Ayush Agarwal",
    url: "https://github.com/ayushhagarwal",
  },
  keywords: [
    "markdown editor",
    "markdown viewer",
    "online markdown editor",
    "online markdown viewer",
    "markdown application",
    "markdown tool",
    "markdown preview",
    "markdown previewer",
    "free markdown viewer",
    "markdown viewer online free",
    "online markdown preview",
    "markdown renderer",
    "markdown to html",
    "pdf to markdown",
    "word to markdown",
    "docx to markdown",
    "confluence pdf to markdown",
    "github markdown editor",
    "github flavored markdown viewer",
    "README editor",
    "README preview",
    "Mermaid markdown editor",
    "markdown math editor",
    "KaTeX markdown",
    "developer writing tool",
    "AI notes markdown",
    "privacy-first markdown editor",
  ],
  features: [
    "Live Markdown editor and preview",
    "GitHub-flavored Markdown rendering",
    "Mermaid diagram rendering",
    "KaTeX math rendering",
    "Syntax-highlighted code blocks",
    "Tables, task lists, strikethrough, and autolinks",
    "Copy Markdown and rendered HTML",
    "Download Markdown files",
    "Import local Markdown files",
    "Convert text-based PDFs to Markdown locally",
    "Convert Word .docx files to Markdown locally",
    "Export rendered Markdown as standalone HTML",
    "Print or save preview as PDF",
    "Local draft autosave with no account required",
    "Keyboard shortcuts for common actions",
    "Light and dark mode",
  ],
};
