export const siteConfig = {
  name: "Markdown Lens",
  url: "https://markdownlens.ayushdev.com",
  githubUrl: "https://github.com/ayushhagarwal/markdown-lens",
  title: "Free PDF & Word to Markdown Converter | Markdown Lens",
  description:
    "Markdown Lens is a free, privacy-first PDF and Word-to-Markdown converter with local document upload, editable Markdown output, GitHub-flavored previews, diagrams, math, code, and tables.",
  shortDescription:
    "Upload text-based PDFs or Word .docx files and convert them locally into editable Markdown with GitHub-style preview, syntax highlighting, autosave, and no account required.",
  author: {
    name: "Ayush Agarwal",
    url: "https://github.com/ayushhagarwal",
  },
  keywords: [
    "markdown editor",
    "markdown viewer",
    "online markdown editor",
    "online markdown viewer",
    "markdown application",
    "markdown tool",
    "markdown preview",
    "markdown previewer",
    "free markdown viewer",
    "markdown viewer online free",
    "online markdown preview",
    "markdown renderer",
    "markdown to html",
    "pdf to markdown",
    "word to markdown",
    "doc to markdown",
    "docx to markdown",
    "pdf to md",
    "word document to markdown",
    "confluence pdf to markdown",
    "github markdown editor",
    "github flavored markdown viewer",
    "README editor",
    "README preview",
    "Mermaid markdown editor",
    "markdown math editor",
    "KaTeX markdown",
    "developer writing tool",
    "AI notes markdown",
    "privacy-first markdown editor",
  ],
  features: [
    "Live Markdown editor and preview",
    "GitHub-flavored Markdown rendering",
    "Mermaid diagram rendering",
    "KaTeX math rendering",
    "Syntax-highlighted code blocks",
    "Tables, task lists, strikethrough, and autolinks",
    "Copy Markdown and rendered HTML",
    "Download Markdown files",
    "Import local Markdown files",
    "Upload PDFs and Word .docx files",
    "Convert text-based PDFs to Markdown locally",
    "Convert Word .docx files to Markdown locally",
    "Export rendered Markdown as standalone HTML",
    "Print or save preview as PDF",
    "Local draft autosave with no account required",
    "Keyboard shortcuts for common actions",
    "Light and dark mode",
  ],
};
